/* Generated by Edge Impulse
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

#include <stdint.h>
#include "model_metadata.h"
#include "anomaly_metadata.h"
#include "tflite-model/tflite_learn_31.h"
#include "tflite-model/tflite_anomaly_36.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"

const char* ei_classifier_inferencing_categories[] = { "blender", "blender+fan", "blender+fan+lamp", "blender+fridge", "blender+fridge+fan", "blender+fridge+fan+lamp", "blender+fridge+lamp", "blender+lamp", "fan", "fridge", "fridge+fan", "lamp", "lamp+fan", "lamp+fridge", "lamp+fridge+fan", "noload" };

uint8_t ei_dsp_config_30_axes[] = { 0, 1 };
const uint32_t ei_dsp_config_30_axes_size = 2;
ei_dsp_config_spectral_analysis_t ei_dsp_config_30 = {
    30, // uint32_t blockId
    4, // int implementationVersion
    2, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "none", // select filter-type
    3.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    1024, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const size_t ei_dsp_blocks_size = 1;
ei_model_dsp_t ei_dsp_blocks[ei_dsp_blocks_size] = {
    { // DSP block 30
        1034,
        &extract_spectral_analysis_features,
        (void*)&ei_dsp_config_30,
        ei_dsp_config_30_axes,
        ei_dsp_config_30_axes_size
    }
};
const ei_config_tflite_graph_t ei_config_tflite_graph_31 = {
    .implementation_version = 1,
    .model = tflite_learn_31,
    .model_size = tflite_learn_31_len,
    .arena_size = tflite_learn_31_arena_size
};

const ei_config_tflite_graph_t ei_config_tflite_graph_36 = {
    .implementation_version = 1,
    .model = tflite_anomaly_36,
    .model_size = tflite_anomaly_36_len,
    .arena_size = tflite_anomaly_36_arena_size
};

const ei_learning_block_config_tflite_graph_t ei_learning_block_config_31 = {
    .implementation_version = 1,
    .block_id = 31,
    .object_detection = 0,
    .object_detection_last_layer = EI_CLASSIFIER_LAST_LAYER_UNKNOWN,
    .output_data_tensor = 0,
    .output_labels_tensor = 1,
    .output_score_tensor = 2,
    .quantized = 0,
    .compiled = 0,
    .graph_config = (void*)&ei_config_tflite_graph_31
};

ei_learning_block_config_anomaly_gmm_t ei_learning_block_config_36 = {
    .implementation_version = 1,
    .anom_axis = ei_classifier_anom_axes,
    .anom_axes_size = 5,
    .graph_config = (void*)&ei_config_tflite_graph_36
};

const size_t ei_learning_blocks_size = 2;
const ei_learning_block_t ei_learning_blocks[ei_learning_blocks_size] = {
    {
        &run_nn_inference,
        (void*)&ei_learning_block_config_31,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
    },
    {
        &run_gmm_anomaly,
        (void*)&ei_learning_block_config_36,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
    },
};

const ei_model_performance_calibration_t ei_calibration = {
    1, /* integer version number */
    false, /* has configured performance calibration */
    (int32_t)(EI_CLASSIFIER_RAW_SAMPLE_COUNT / ((EI_CLASSIFIER_FREQUENCY > 0) ? EI_CLASSIFIER_FREQUENCY : 1)) * 1000, /* Model window */
    0.8f, /* Default threshold */
    (int32_t)(EI_CLASSIFIER_RAW_SAMPLE_COUNT / ((EI_CLASSIFIER_FREQUENCY > 0) ? EI_CLASSIFIER_FREQUENCY : 1)) * 500, /* Half of model window */
    0   /* Don't use flags */
};

const ei_impulse_t impulse_280875_7 = {
    .project_id = 280875,
    .project_owner = "Brennan's Lab",
    .project_name = "Imagine-Demo-All-Permutations",
    .deploy_version = 7,

    .nn_input_frame_size = 1034,
    .raw_sample_count = 40,
    .raw_samples_per_frame = 2,
    .dsp_input_frame_size = 40 * 2,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1,
    .frequency = 1000,
    .dsp_blocks_size = ei_dsp_blocks_size,
    .dsp_blocks = ei_dsp_blocks,
    
    .object_detection = 0,
    .object_detection_count = 0,
    .object_detection_threshold = 0,
    .object_detection_last_layer = EI_CLASSIFIER_LAST_LAYER_UNKNOWN,
    .fomo_output_size = 0,
    
    .tflite_output_features_count = 16,
    .learning_blocks_size = ei_learning_blocks_size,
    .learning_blocks = ei_learning_blocks,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "volt + curr",
    .slice_size = (40/4),
    .slices_per_model_window = 4,

    .has_anomaly = 1,
    .label_count = 16,
    .calibration = ei_calibration,
    .categories = ei_classifier_inferencing_categories
};

const ei_impulse_t ei_default_impulse = impulse_280875_7;

#endif // _EI_CLASSIFIER_MODEL_METADATA_H_
